apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: helloWorld
    env: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: helloWorld
    spec:
      containers:
      - image: dhire/java_tomcat
        name: helloWorld
        ports:
        - name: helloWorld
          containerPort: 80
----
#Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: helloWorld
spec:
  type: NodePort
  ports:
    - port:80
      targetPort: 80
  selector:
    name:
