apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatdeployment
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: dev_tomcatapp
  replicas: 1
  template:
    metadata:
      labels:
        app: dev_tomcatapp
    spec:
      containers:
      - name: tomcat
        image: dhire/java_tomcat
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      nodeSelector:
        env: dev
        
---
apiVersion: v1
kind: Service
metadata:
  name: dev_tomcatapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: dev_tomcatapp
    
