apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatdeployment
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: tomcatapp
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcatapp
    spec:
      containers:
      - name: tomcat
        image: dhire/java_tomcat
        ports:
        - containerPort: 80
      nodeSelector:
        env: dev
        
---
apiVersion: v1
kind: Service
metadata:
  name: tomcatapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: tomcatapp
